# Generated by Django 5.1.2 on 2024-10-31 17:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(default='nombre@ejemplo.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=300)),
                ('email', models.EmailField(default='nombre@ejemplo.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=300)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('director', models.CharField(max_length=300)),
                ('sinopsis', models.TextField(null=True)),
                ('fechaLanzamiento', models.DateField(default=django.utils.timezone.now)),
                ('tiempoProyectada', models.DurationField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=9)),
                ('web', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=300)),
                ('nuss', models.CharField(max_length=12, unique=True)),
                ('iban', models.CharField(max_length=24, unique=True)),
                ('salario', models.IntegerField(default=1100)),
                ('encargado', models.BooleanField(default=False)),
                ('cine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCine.cine')),
            ],
        ),
        migrations.AddField(
            model_name='cine',
            name='gerente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GestionCine.gerente'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('co', 'comida'), ('be', 'bebida')], default='co', max_length=2)),
                ('fechaCaducidad', models.DateField(default=django.utils.timezone.now)),
                ('cliente', models.ManyToManyField(to='GestionCine.cliente')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCine.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCine.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCompra', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='GestionCine.cliente')),
                ('proyeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCine.proyeccion')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano', models.CharField(choices=[('PE', 'Pequena'), ('ME', 'Mediana'), ('GR', 'Grande')], default='ME', max_length=2)),
                ('cine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCine.cine')),
                ('empleado', models.ManyToManyField(to='GestionCine.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='proyeccion',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCine.sala'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sala',
            field=models.ManyToManyField(to='GestionCine.sala'),
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numSocio', models.CharField(max_length=5, unique=True)),
                ('fechaAlta', models.DateField(default=django.utils.timezone.now)),
                ('fechaCaducidad', models.DateField(default=django.utils.timezone.now)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GestionCine.cliente')),
            ],
        ),
    ]
