# Generated by Django 5.1.2 on 2025-01-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
