# Generated by Django 5.1.2 on 2024-10-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='tamaño',
        ),
        migrations.AddField(
            model_name='sala',
            name='tamano',
            field=models.CharField(choices=[('PE', 'Pequena'), ('ME', 'Mediana'), ('GR', 'Grande')], default='ME', max_length=2),
        ),
    ]
