# Generated by Django 5.1.2 on 2024-10-22 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCine', '0002_remove_sala_tamaño_sala_tamano'),
    ]

    operations = [
        migrations.AddField(
            model_name='cine',
            name='email',
            field=models.EmailField(default='nombre@ejemplo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='nombre@ejemplo.com', max_length=254),
        ),
        migrations.AddField(
            model_name='empleado',
            name='salario',
            field=models.IntegerField(default=1100),
        ),
        migrations.AddField(
            model_name='entrada',
            name='fechaCompra',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='fechaLanzamiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='tiempoProyectada',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fechaCaducidad',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='web',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='proyeccion',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='socio',
            name='fechaAlta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='socio',
            name='fechaCaducidad',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
