# Generated by Django 5.1.2 on 2024-11-03 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCine', '0002_alter_empleado_cine_alter_entrada_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socios_cliente', to='GestionCine.cliente'),
        ),
    ]
